version: "3.9"
services:
  spotinlizer:
    image: spotinlizer:latest
    build: .
    entrypoint: python /main.py --known_lyrics "THE TEXT I WANT TO LOOK FOR MATE" --likeliness_threshold 1.5
    volumes:
      - ./main.py:/main.py
      - ./lyrics_utils.py:/lyrics_utils.py
      - .cache:/.cache

    environment:
      - SPOTIFY_CLIENT_ID=FILL
      - SPOTIFY_CLIENT_SECRET=FILL
      - SPOTIFY_REDIRECT_URI=FILL
      - GENIUS_ACCESS_TOKEN=FILL
